config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/login', to: 'sessions#new', as: 'login'
  get 'dashboard', to: 'users#dashboard', as: 'dashboard'
  resources :blacklisted_repos, only: [:create, :destroy, :index]
  root to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blacklisted_repo.rb
# frozen_string_literal: true

class BlacklistedRepo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :blacklisted_repos, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id].present?
  end

  before_action :authenticate_user!

  private

  def authenticate_user!
    return if current_user

    redirect_to login_path, alert: 'Please log in to view your dashboard.'
  end
end

app/controllers/blacklisted_repos_controller.rb
# frozen_string_literal: true

class BlacklistedReposController < ApplicationController
  def index
    blacklisted_repos = current_user.blacklisted_repos
    render :index, locals: { blacklisted_repos:, current_user: }
  end

  def create
    current_user.blacklisted_repos.create(blacklisted_repo_name: params[:blacklisted_repo_name])
    flash[:notice] = 'Repository added to blacklist'
    redirect_to dashboard_path
  end

  def destroy
    current_user.blacklisted_repos.find_by(blacklisted_repo_name: params[:blacklisted_repo_name])&.destroy
    flash[:notice] = 'Repository removed from blacklist'
    redirect_to blacklisted_repos_path
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new create]
  def new; end

  def create
    auth = request.env['omniauth.auth']
    user = User.find_or_create_by(uid: auth['uid'])
    user.email = auth['info']['email']
    user.github_access_token = auth['credentials']['token']
    user.save
    session[:user_id] = user.id
    redirect_to '/dashboard', notice: 'Logged in!'
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def dashboard
    github_gateway = GithubGateway.new(current_user.github_access_token)
    repositories = RepositoryService.call(current_user, github_gateway, params[:query])
    repo_names = repositories.pluck('name')
    render 'dashboard', locals: { repo_names:, repositories: }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blacklisted_repos/index.html.erb
<h1>Blacklisted Repositories</h1>

<ul>
  <%  blacklisted_repos.each do |blacklist| %>
          <li style="display: flex; align-items: center; gap: 10px;">
      <%= blacklist.blacklisted_repo_name %>
      <%= button_to 'Remove from Blacklist', blacklisted_repo_path(current_user, blacklisted_repo_name: blacklist.blacklisted_repo_name), method: :delete %>
    </li>
  <% end %>
</ul>

<%= button_to 'Back to Dashboard', dashboard_path, method: :get %>

app/views/layouts/_flash_msg.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success">
        <%= flash[:notice] %>
     </div>
 <% elsif flash[:alert] %>
    <div class="alert alert-danger">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="nav-button">
  <nav>
    <span class="button">
      <a href="/">Home</a>
      <a href="/dashboard">Dashboard</a>
      <a href="/blacklisted_repos">Blacklisted Repositories</a>
      <a href="/logout">Logout</a>
    </span>
  </nav>
</div>

    <%= render 'layouts/flash_msg'%>
    <%= yield %>
  </body>
</html>

app/views/users/dashboard.html.erb
<h1>Welcome, <%= current_user.email %>!</h1>

<form method="get" action="/dashboard">
  <input type="text" list="repo-names" name="query">
  <datalist id="repo-names">
    <% repo_names.each do |name| %>
      <option value="<%= name %>"></option>
    <% end %>
  </datalist>
  <input type="submit" value="Search">
</form>

<h2>Your GitHub Repositories:</h2>

<ul>
 <% if repositories.any? %>
  <% repositories.each do |repo| %>
          <li style="display: flex; align-items: center; gap: 10px;">
      <%= repo['name'] %> - <%= repo['star_count'] %> stars
    <%= button_to 'Blacklist', blacklisted_repos_path( blacklisted_repo_name:  repo['name']), method: :post%></li>
</li>
  <% end %>
<% else %>
  <li>No matches found</li>
<% end %>

</ul>
<%= button_to 'Black List', blacklisted_repos_path, method: :get%>
<%= button_to 'Logout', logout_path, method: :get %>